language: node_js
node_js:
- 4.1
sudo: false
cache:
  directories:
    - node_modules
notifications:
  email:
    - torstenlink@gmx.de
    - markus.felten@gmx.de
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
after_success:
  - npm run semantic-release
